# -*- coding: utf-8 -*-
"""day1Advent2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRen_Pi1dDlXRi-Tf_icRaJSjfhUSXF1
"""

import pandas as pd
import numpy as np

# import data from input.txt

data = pd.read_csv('input.txt', header=None)

data.head()

data[0][0].split()

middle = round(len(data[0][0]) / 2)

sumTotal = int(data[0][0][middle:]) - int(data[0][0][:middle])

print(sumTotal)



grandTotal = 0
list1 = []
list2 = []
for row in data[0]:
    list1.append(int(row[middle:]))
    list2.append(int(row[:middle]))
print(grandTotal)

list1Sorted = list1.sort()
list2Sorted = list2.sort()



for i in range(len(list1)):
    sumTotal = list1[i] - list2[i]
    grandTotal += abs(sumTotal)

print(grandTotal)